# 🗓️ Lamarck 2025-11-22

In [1]:
import torch

求导是几乎所有深度学习优化算法的关键步骤。 虽然求导的计算很简单，只需要一些基本的微积分。 但对于复杂的模型，手工进行更新是一件很痛苦的事情（而且经常容易出错）。

深度学习框架通过自动计算导数，即自动微分（automatic differentiation）来加快求导。 实际中，根据设计好的模型，系统会构建一个计算图（computational graph）， 来跟踪计算是哪些数据通过哪些操作组合起来产生输出。 自动微分使系统能够随后反向传播梯度。 这里，反向传播（backpropagate）意味着跟踪整个计算图，填充关于每个参数的偏导数。

## 2.5.1 一个简单的例子

定义一个函数y=2XT*X，关于列向量x求导。首先，我们创建变量x，并为其分配一个初始值。

In [3]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

x.requires_grad_(True) -- 让张量x开启梯度跟踪（gradient tracking）。之后所有对x的运算（加、减、乘、点积、矩阵乘法、激活函数……），PyTorch 都会记录在计算图 (computational graph) 中。

In [4]:
x.requires_grad_(True)  # 等价于x=torch.arange(4.0,ruires_grad=True)
x.grad  # 还没调用backward()之前，这里的默认值是None

函数y=2XT*X，关于x的梯度应该为4x，验证一下这个梯度是否计算正确

In [10]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

调用反向传播函数来自动计算y关于x每个分量的梯度，并打印这些梯度。

In [6]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

快速验证这个梯度是否计算正确。

In [7]:
x.grad == 4 * x

tensor([True, True, True, True])

现在计算x的另一个函数。

In [11]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])